name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:

  build-desktop:

    runs-on: windows-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17


      - name: Install WiX
        run: choco install wixtoolset -y


      # 🔥 BUILD REAL
      - name: Build Installers
        run: |
          .\gradlew.bat clean
          .\gradlew.bat packageMsi
          .\gradlew.bat packageExe


      # 🔍 DEBUG
      - name: Show Build Files
        run: |
          dir composeApp\build /s


      # 📦 PREPARAR ARCHIVOS
      - name: Prepare Artifacts
        shell: pwsh
        run: |

          mkdir artifacts -Force

          Get-ChildItem -Recurse -Filter *.msi | % {
              Copy-Item $_ artifacts\TicTacToe-${{ github.ref_name }}.msi
          }

          Get-ChildItem -Recurse -Filter *.exe | % {
              Copy-Item $_ artifacts\TicTacToe-${{ github.ref_name }}.exe
          }

          dir artifacts


      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: artifacts/*



  release:

    needs: build-desktop

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - uses: actions/download-artifact@v4
        with:
          name: windows


      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            *.msi
            *.exe

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}